name: Build umx for R

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.2', '4.4.1']
    steps:
      - uses: actions/checkout@v4
        with:
          path: ~/.R/library
          key: ${{ runner.os }}-r-${{ matrix.r-version }}-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ matrix.r-version }}-
            ${{ runner.os }}-r-
      - uses: actions/checkout@v4
      - name: Install system dependencies
		run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev librsvg2-dev
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "covr", "OpenMx", "mvtnorm", "DiagrammeRsvg", "rsvg"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check package
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
          devtools::check()
        shell: Rscript {0}
      - name: Code Coverage
        run: covr::codecov()
        shell: Rscript {0}
